### ISSUE TITLE
vue引入报错

### ISSUE THREAD

**Issue by cyfour** [MisterChangRay/Mtils2#2]
./node_modules/mtils/index.js
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| 
| 
 @ ./node_modules/babel-loader/lib!./node_modules/vux-loader/src/script-loader.js!./node_modules/vux-loader/src/script-loader.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/moneyMakingInformation/moneyMakingInformation.vue 8:0-26
 @ ./src/pages/moneyMakingInformation/moneyMakingInformation.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.8.210.172:8080 webpack/hot/dev-server ./src/main.js

**Comment by MisterChangRay** [comment]
你好.
这里的index.js是提供给node.js调用的.
建议直接在index.html 中全局引入 Mtils.js
或者在 webpack 配置文件中 使用 alias 配置,然后再引入使用。

**Comment by MisterChangRay** [comment]
现在你可以下载最新的源码引入；
