### ISSUE TITLE
在vue cli webpack下面直接import不能用啊，只能在node环境下使用

### ISSUE THREAD

**Issue by tianyazjq** [MisterChangRay/Mtils2#3]
在vue cli webpack下面直接import不能用啊，只能在node环境下使用，针对vue+webpack的没有办法直接使用，看看Es6语法啥改造一下。

**Comment by tianyazjq** [comment]
我现在的改造方式
function isMobile(str_data) {
  str_data = str_data || String(this);
  var length = str_data.length;
  return length == 11 && /^1\d{10}$/.test(str_data);
}

export default {
  formatTime,
  formatTimeSecond,
  ab2hex,
  isNumeric,
  devInfo,
  checkIdCard,
  setStor,
  isEmptyObj,
  isMobile
};

使用方法：
 import Utils from '../utils/util.js'

**Comment by MisterChangRay** [comment]
好的，这个问题会在下个版本修复。多谢；
